### ISSUE TITLE
Unable to remove the plugin !!

### ISSUE THREAD

**Issue by seme1** [getsentry/sentry-cordova#85]
I've wasted over two hours attempting to remove the plugin from my Android project with no success.  The project is hosted on a Windows 10 machine.
There also seems to be a hook running every time I attempt to remove the plugin.

```
`C:\project>cordova plugin rm sentry-cordova --save --froce
Sentry: running before_plugin_rm - set SENTRY_SKIP_WIZARD=true to skip this
no URL provided, fallback to https://sentry.io/
Running Sentry Wizard...
version: 0.10.3 | sentry-cli version: 1.35.5

😢  Successfully removed Sentry from your project 😢

C:\project>cordova plugin ls
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"
sentry-cordova 0.12.3 "Sentry"

C:\project>cordova platform -v
8.0.0

C:\project>cordova platform version android
Installed platforms:
  android 6.3.0
```

**Comment by HazAT** [comment]
can you try this:
`SENTRY_SKIP_WIZARD=true cordova plugin rm sentry-cordova --save --force`

**Comment by neilbo** [comment]
For my Ionic 3 project: I had to go the plugins folder, 

1. delete the sentry-cordova directory, 
2. files remove all references to sentry-cordova in the: 
- android.json
- browser.json
- fetch.json
- ios.json

**Comment by jamesdixon** [comment]
I basically had to blow everything away (platforms, plugins, node_modules) to get this thing removed. Terrible uninstall process... 👎

**Comment by mgrubinger** [comment]
+1
`cordova plugin rm sentry-cordova` won't actually remove the plugin :(

**Comment by boynet** [comment]
+1? for me I get "Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it."

**Comment by miladmeidanshahi** [comment]
the same issue still I have problem

**Comment by richardshergold** [comment]
We use raven.js in our Ionic project so I was looking to upgrade to the Cordova Plugin but if issues like this (over a year old) are still open does that suggest I should wait?  I don't want to add a plugin that (from the evidence here) is difficult to remove.  Is this still an issue?

**Comment by PowerMogli** [comment]
We still have the same problems as mentioned by @boynet 

> +1? for me I get "Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it."

**Comment by dhandarbeit-tk** [comment]
This is disgusting. I couldnt get the package running in development so i tried to remove it. Obviously sentry uses a couple of techniques that are not standard for the cordova boilerplate. But this is the most annoying issue. Please fix this as soon as possible.

**Comment by HazAT** [comment]
Hey sorry about the issue this is not intended if you are still running into:
`"Using "requireCordovaModule" to load non-cordova module "fs" is not supported.`
This has been fixed in march already: (after version `> 0.14`)
https://github.com/getsentry/sentry-cordova/commit/8e5eb67b22d6dfc0996d9f9c9ac7efb70ce93866#diff-c7f37af3816a5a9970457d017658c9f5

Please change the line in your plugin folder to just require.
After that removing the plugin like `SENTRY_SKIP_WIZARD=true cordova plugin rm sentry-cordova` has to work.

**Comment by teamgeist-app** [comment]
Still having the same problem when uninstalling the plugin. References and files remain cluttered all over the app (despite the fact, that i couldn't get it to run).

I switched to the browser version but the remains of the cordova plugin kept screwing my build process...

**Comment by sebj54** [comment]
I struggled with this plugin but after reading a few docs, I made it work!

 Add a `.env` at the root of your project with this content: 

```
SENTRY_SKIP_WIZARD=true
```

Try deleting again!

**Comment by slothstronaut** [comment]
> ENTRY_SKIP_WIZARD=true cordova plugin rm sentry-cordova

This does not work. Super disappointed this plugin is wasting my time by referencing a broken plugin.

Do not install verison sentry-cordova@0.12.3 as their documentation tells you to, this version will screw your cordova install like mine is.

Thanks for wasting my time.

**Comment by rastilin** [comment]
I can confirm that...

`cordova plugin add sentry-cordova`

..does work, though it's probably a good idea to update the documentation.
